package com.github.abraga.verdandi.api.scope

import com.github.abraga.verdandi.internal.core.grammar.Plural
import com.github.abraga.verdandi.internal.core.grammar.Singular

interface QuantityUnitSelector<out R> : TemporalUnitProvider {

    fun build(count: Int, unit: TemporalUnit<*>): R

    infix fun zero(unit: TemporalUnit<Plural>) = build(0, unit)
    infix fun one(unit: TemporalUnit<Singular>) = build(1, unit)
    infix fun two(unit: TemporalUnit<Plural>) = build(2, unit)
    infix fun three(unit: TemporalUnit<Plural>) = build(3, unit)
    infix fun four(unit: TemporalUnit<Plural>) = build(4, unit)
    infix fun five(unit: TemporalUnit<Plural>) = build(5, unit)
    infix fun six(unit: TemporalUnit<Plural>) = build(6, unit)
    infix fun seven(unit: TemporalUnit<Plural>) = build(7, unit)
    infix fun eight(unit: TemporalUnit<Plural>) = build(8, unit)
    infix fun nine(unit: TemporalUnit<Plural>) = build(9, unit)
    infix fun ten(unit: TemporalUnit<Plural>) = build(10, unit)
    infix fun eleven(unit: TemporalUnit<Plural>) = build(11, unit)
    infix fun twelve(unit: TemporalUnit<Plural>) = build(12, unit)
    infix fun thirteen(unit: TemporalUnit<Plural>) = build(13, unit)
    infix fun fourteen(unit: TemporalUnit<Plural>) = build(14, unit)
    infix fun fifteen(unit: TemporalUnit<Plural>) = build(15, unit)
    infix fun sixteen(unit: TemporalUnit<Plural>) = build(16, unit)
    infix fun seventeen(unit: TemporalUnit<Plural>) = build(17, unit)
    infix fun eighteen(unit: TemporalUnit<Plural>) = build(18, unit)
    infix fun nineteen(unit: TemporalUnit<Plural>) = build(19, unit)
    infix fun twenty(unit: TemporalUnit<Plural>) = build(20, unit)
    infix fun twentyOne(unit: TemporalUnit<Plural>) = build(21, unit)
    infix fun twentyTwo(unit: TemporalUnit<Plural>) = build(22, unit)
    infix fun twentyThree(unit: TemporalUnit<Plural>) = build(23, unit)
    infix fun twentyFour(unit: TemporalUnit<Plural>) = build(24, unit)
    infix fun twentyFive(unit: TemporalUnit<Plural>) = build(25, unit)
    infix fun twentySix(unit: TemporalUnit<Plural>) = build(26, unit)
    infix fun twentySeven(unit: TemporalUnit<Plural>) = build(27, unit)
    infix fun twentyEight(unit: TemporalUnit<Plural>) = build(28, unit)
    infix fun twentyNine(unit: TemporalUnit<Plural>) = build(29, unit)
    infix fun thirty(unit: TemporalUnit<Plural>) = build(30, unit)
    infix fun thirtyOne(unit: TemporalUnit<Plural>) = build(31, unit)
    infix fun thirtyTwo(unit: TemporalUnit<Plural>) = build(32, unit)
    infix fun thirtyThree(unit: TemporalUnit<Plural>) = build(33, unit)
    infix fun thirtyFour(unit: TemporalUnit<Plural>) = build(34, unit)
    infix fun thirtyFive(unit: TemporalUnit<Plural>) = build(35, unit)
    infix fun thirtySix(unit: TemporalUnit<Plural>) = build(36, unit)
    infix fun thirtySeven(unit: TemporalUnit<Plural>) = build(37, unit)
    infix fun thirtyEight(unit: TemporalUnit<Plural>) = build(38, unit)
    infix fun thirtyNine(unit: TemporalUnit<Plural>) = build(39, unit)
    infix fun forty(unit: TemporalUnit<Plural>) = build(40, unit)
    infix fun fortyOne(unit: TemporalUnit<Plural>) = build(41, unit)
    infix fun fortyTwo(unit: TemporalUnit<Plural>) = build(42, unit)
    infix fun fortyThree(unit: TemporalUnit<Plural>) = build(43, unit)
    infix fun fortyFour(unit: TemporalUnit<Plural>) = build(44, unit)
    infix fun fortyFive(unit: TemporalUnit<Plural>) = build(45, unit)
    infix fun fortySix(unit: TemporalUnit<Plural>) = build(46, unit)
    infix fun fortySeven(unit: TemporalUnit<Plural>) = build(47, unit)
    infix fun fortyEight(unit: TemporalUnit<Plural>) = build(48, unit)
    infix fun fortyNine(unit: TemporalUnit<Plural>) = build(49, unit)
    infix fun fifty(unit: TemporalUnit<Plural>) = build(50, unit)
    infix fun fiftyOne(unit: TemporalUnit<Plural>) = build(51, unit)
    infix fun fiftyTwo(unit: TemporalUnit<Plural>) = build(52, unit)
    infix fun fiftyThree(unit: TemporalUnit<Plural>) = build(53, unit)
    infix fun fiftyFour(unit: TemporalUnit<Plural>) = build(54, unit)
    infix fun fiftyFive(unit: TemporalUnit<Plural>) = build(55, unit)
    infix fun fiftySix(unit: TemporalUnit<Plural>) = build(56, unit)
    infix fun fiftySeven(unit: TemporalUnit<Plural>) = build(57, unit)
    infix fun fiftyEight(unit: TemporalUnit<Plural>) = build(58, unit)
    infix fun fiftyNine(unit: TemporalUnit<Plural>) = build(59, unit)
}
